version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: cd frontend; npm install
      - run: 
          name: Run Tests
          command: cd frontend; npm run test:unit
  build:
    docker:
      - image: cimg/ruby:2.7.5
    steps:
      - checkout
      - run: 
          name: Check versions
          command: ruby --version
      
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-deploy:
    jobs:
      - test
