version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  test_and_build_vue:
    docker:
      - image: cimg/node:14.13.0
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: cd frontend; npm install
      - run: 
          name: Run Tests
          command: cd frontend; npm run test:unit
      - run: 
          name: Build
          command: cd frontend; npm run build
  
  build_test_rails:
    docker:
      - image: cimg/ruby:2.7-node
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
      - image: cimg/postgres:14.0
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
        environment: # add POSTGRES environment variables.
            POSTGRES_USER: postgres
            POSTGRES_DB: todo_rails_vuejs
            POSTGRES_PASSWORD: password
    environment:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: password
      RAILS_ENV: development
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m      
      - run: 
          name: Install dependencies 2
          command: cd backend; gem install bundler --version 2.2.3; bundle install;      
      - run:
          name: Database migrations
          command: cd backend; bundle exec rails db:migrate
      # - run: 
      #     name: Starting app server
      #     command: cd backend; rails s -p 3000 -b '0.0.0.0'
  aws-ecr/build-and-push-image:
    docker:
      - image: cimg/node:14.13.0
        auth:
            username: $DOCKERHUB_USER
            password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: Start build and push image to AWS-ECR
          command: clear
  
      - aws-ecr/build-and-push-image:
          dockerfile: backend/Dockerfile
          repo: rails6_vuejs
          region: AWS_REGION
          checkout: false

workflows:
  test_and_build:
    jobs:
      - test_and_build_vue
      - build_test_rails:
          requires:
            - test_and_build_vue
          filters:
            branches:
              only:
                - master
      - aws-ecr/build-and-push-image:
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "${CIRCLE_SHA1}"

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run this job once aws-ecr/build-and-push-image has completed
          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
        