version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: 
          name: where i am
          command: ls -la
      - run: 
          name: move
          command: cd frontend/
      - run: 
          name: where i am 2
          command: ls -la   
      
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-deploy:
    jobs:
      - test
