version: 2.1

jobs:
  test_and_build_vue:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: cd frontend; npm install
      - run: 
          name: Run Tests
          command: cd frontend; npm run test:unit
      - run: 
          name: Build and Run
          command: cd frontend; npm run serve
  
  build_test_rails:
    docker:
      - image: cimg/ruby:2.7.5
      - image: cimg/postgres:13.0
    environment:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: password
      RAILS_ENV: dev
    steps:
      - checkout
      - run: 
          name: Install dependencies 1
          command: apt-get update -qq && apt-get install -y postgresql-client
      - run: 
          name: Install dependencies 2
          command: cd backend; gem install bundler --version 2.2.3; bundle install;
      - run: 
          name: Run migrations
          command: rails db:migrate
      - run: 
          name: Starting app server
          command: rails s -p 3000 -b '0.0.0.0'
      
workflows:
  test_and_build:
    jobs:
      - test_and_build_vue:
      - build_test_rails:
          requires:
            - test_and_build_vue
          filters:
            branches:
              only:
                - master