version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
          name: Move into frontend
          command: cd frontend
      - run: 
          name: Install dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test:unit

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-deploy:
    jobs:
      - test
